import {
  ARENA_WIDTH,
  ARENA_HEIGHT,
  VIEWPORT_WIDTH,
  VIEWPORT_HEIGHT,
} from '../../data/balance';
import { getBattleTargetKills } from '../../data/battleTemplates';
import type {
  BattleState,
  BattleTemplateDefinition,
  NodeOption,
  RunState,
} from '../../game/types';

const CENTER_X = ARENA_WIDTH / 2;
const CENTER_Y = ARENA_HEIGHT / 2;

export interface CreateBattleStateParams {
  node: NodeOption;
  template: BattleTemplateDefinition;
  dashInterval: number;
  activeRoutePerks?: RunState['activeRoutePerks'];
}

export function createBattleState(params: CreateBattleStateParams): BattleState {
  const encounterType = params.template.encounterType ?? (params.node.type === 'boss' ? 'boss' : 'battle');
  const battleLabel = encounterType === 'boss' ? `Boss \u00b7 ${params.node.title}` : params.template.name;
  const perks = params.activeRoutePerks ?? {};

  return {
    encounterType,
    templateId: params.template.id,
    label: battleLabel,
    description:
      encounterType === 'boss'
        ? `${params.node.description} ${params.template.description}`
        : params.template.description,
    durationSec: params.template.durationSec,
    remainingSec: params.template.durationSec,
    targetKills: getBattleTargetKills(params.template.id),
    spawnIntervalSec: params.template.spawnIntervalSec,
    enemyHp: 0,
    enemySpeed: 0,
    difficultyScale: params.node.difficultyScale ?? 1,
    kills: 0,
    elapsedSec: 0,
    pressurePhaseIndex: -1,
    pressurePhaseElapsedSec: 0,
    pressurePhaseLabel: params.template.eliteRule ? (encounterType === 'boss' ? '接敌' : '交火') : undefined,
    pressureTransitionSec: 0,
    pressureSignatureLabel: undefined,
    pressureSignatureSec: 0,
    pressureSignaturePulseSec: 0,
    pressurePatternLabel: undefined,
    pressurePatternMode: undefined,
    pressurePatternPulseSec: 0,
    pressurePatternFlashSec: 0,
    pressurePatternPulseCount: 0,
    pressureSafeWindowAxis: undefined,
    pressureSafeWindowShiftType: undefined,
    pressureSafeWindowCenter: CENTER_X,
    pressureSafeWindowSpan: 0,
    pressureSafeWindowSecondaryCenter: CENTER_Y,
    pressureSafeWindowSecondarySpan: 0,
    pressureSafeWindowSec: 0,
    pressurePocketShiftSeen: [],
    nextEnemyId: 0,
    nextBulletId: 0,
    nextPulseId: 0,
    nextEnemyProjectileId: 0,
    enemySpawnTimerSec: 0.2,
    eliteSupportCooldownSec: 0,
    spawnCursor: 0,
    fireCooldownSec: 0.1,
    dashCooldownSec: params.dashInterval,
    invulnerableSec: 0,
    impactFreezeSec: 0,
    impactFreezeFactor: 1,
    enemies: [],
    bullets: [],
    pulses: [],
    experienceOrbs: [],
    enemyProjectiles: [],
    playerX: CENTER_X,
    playerY: CENTER_Y,
    playerVelocityX: 0,
    playerVelocityY: 0,
    playerMoveDirX: 0,
    playerMoveDirY: 0,
    playerAimDirX: 0,
    playerAimDirY: -1,
    eliteAlive: false,
    eliteSpawned: false,
    eliteCrackWindowSec: 0,
    eliteCrackEscortCount: 0,
    eliteBreachFlashSec: 0,
    eliteBreachCalloutCooldownSec: 0,
    critOverdriveSec: 0,
    critChain: 0,
    dashCharge: 0,
    dashDriveSec: 0,
    playerKnockbackVX: 0,
    playerKnockbackVY: 0,
    playerImpactSec: 0,
    playerRecoverySec: 0,
    killFlowSec: 0,
    killFlowCount: 0,
    killStreakCount: 0,
    killStreakDecaySec: 0,
    killStreakMultiplier: 1.0,
    pierceFlowSec: 0,
    pierceFlowCount: 0,
    pickupFlowSec: 0,
    pickupFlowCount: 0,
    pickupLeadSec: 0,
    pickupLeadEnemyId: null,
    playerDamageFlashSec: 0,
    playerDamageAngle: -Math.PI / 2,
    cameraShakeSec: 0,
    cameraShakeStrength: 0,
    cameraShakeFrequency: 11,
    tempoPulseSec: 0,
    playerShotFlashSec: 0,
    playerShotRecoilSec: 0,
    playerShotRecoilStrength: 0,
    playerMoveBoostSec: 0,
    playerTurnBurstSec: 0,
    playerNearMissSec: 0,
    playerNearMissAngle: -Math.PI / 2,
    playerNearMissCooldownSec: 0,
    lateDashWindowMoments: 0,
    dashCounterMoments: 0,
    dashCounterWindowSec: 0,
    eliteCrackSeen: false,
    eliteCrackFollowThroughMoments: 0,
    bossFirelineCoverage: 0,
    bossSafeWindowMoments: 0,
    bossSafeWindowGraceSec: 0,
    outsideSafeDamageTimerSec: 0,
    outsideSafeDamageTickCount: 0,
    insideSafeProjectileClears: 0,
    killPickupContinueMoments: 0,
    monitorDashLateMomentCooldownSec: 0,
    monitorDashCounterCooldownSec: 0,
    monitorEliteCrackFollowThroughCooldownSec: 0,
    monitorKillPickupContinueCooldownSec: 0,
    pierceSeamkeepActive: perks.pierceSeamkeep ?? false,
    pierceFloodgateReady: perks.pierceFloodgate ?? false,
    pierceRiftbloomActive: (perks.pierceRiftbloom ?? false) || (perks.piercePrism ?? false),
    dashBrushActive: perks.dashBrush ?? false,
    dashSidestepBankActive: perks.dashSidestepBank ?? false,
    dashZeroWindowReady: perks.dashZeroWindow ?? false,
    dashAfterimageReady: perks.dashAfterimage ?? false,
    critAfterglowActive: perks.critAfterglow ?? false,
    critEmbershardActive: perks.critEmbershard ?? false,
    critCrownfireReady: perks.critCrownfire ?? false,
    critBurstBonusSec: 0,
    critBurstBonusRatio: 0,
    critFocusTargetId: null,
    critFocusLockSec: 0,
    critComboStacks: 0,
    critComboDecaySec: 0,
    critFinisherReady: false,
    critBurstChainSec: 0,
    critBurstChainCount: 0,
    pierceFractureMark: new Set<number>(),
    pierceChainStacks: 0,
    pierceChainDecaySec: 0,
    dashAfterimages: [],
    dashConsecutiveCount: 0,
    dashConsecutiveWindowSec: 0,
    dashGhostStrikeReady: false,
    dashMomentumStacks: 0,
    dashMomentumDecaySec: 0,
  };
}
