export {
  calculateCritOverdriveDuration,
  calculateEffectiveFireRate,
  calculateEffectiveCritChance,
  calculateCritSplashRatio,
  calculateDashPulseDamage,
  calculateDashPulseRadius,
  calculateDashDriveDuration,
  calculateDashCooldownAfterPulse,
  calculateDashPulseHeal,
  calculateDashDamageMultiplier,
  calculatePierceEchoCount,
  calculatePierceEchoDamageRatio,
  calculatePierceCooldownRefund,
} from './DamageCalculator';
